# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a13bf613b8417427562e27a69f1a628c5a4b37fff02efbab7e849803106e4c3ed924bbdc5894c086dd67c09ee4fa1a3b13c2eaaed922f8bb1741094961ccf50

test:
  secret_key_base: 67a36153a54eb4353b2803c286535526da0acacf9c03033ef23c2f14fec6e0c8e1c692a533aae960aa3c24ebf5fd0b3625ef3244c95e9ef46d1a3668d3228348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
